### ISSUE TITLE
TSlint 5.x

### ISSUE THREAD

**Issue by szebrowski** [Sergiioo/tslint-defocus#1]
Hi,
is it possible that this plugin is not compatible with TSlint version 5.x? :)

I swore I seen it working in my project but after updating to 5.x there are no errors.

**Comment by Sergiioo** [comment]
Yup - good catch. I'm also seeing it fail to flag a warning under TSLint 5. I'll take a look ASAP.

**Comment by chillinski** [comment]
What is the current state of this? Any progress yet?

**Comment by Sergiioo** [comment]
Sorry for the slow response - I started trying a fix that was backwards compatible with older versions of tslint, but turned out to be non-trivial. I've now got a working tslint v5 only version that I'm just testing now and will publish shortly.

**Comment by Sergiioo** [comment]
Fixed in 2.0.2 and published to npm.
