### ISSUE TITLE
Remove @types from dependencies

### ISSUE THREAD

**Issue by robert-gruner** [Sergiioo/tslint-defocus#2]
Hi Sergiioo,

we would like to include your lib (v 2.0.2) into our project but unfortunately it installs further TS types which conflict with our previously used types (mocha vs. jasmine). Would be great if you could remove them from the deps in your package.json and put them to the devDependencies and republish the version or publish a new version for it.

Thx in advance!

**Comment by Sergiioo** [comment]
Yup - good call. Those `@types` references should definitely live in `devDependencies`. I've moved them and published version 2.0.3 to npm.
