### ISSUE TITLE
Package cannot be used in a shared library

### ISSUE THREAD

**Issue by Waldo000000** [Sergiioo/tslint-defocus#5]
It is not possible to use `tslint-defocus` in shared libraries. Specifically, when `tslint-defocus` rules are defined via `rulesDirectory` in a shared library, which is then consumed by other libraries, running tslint on the other libraries leads to a `Could not find custom rule directory` error.

This has been reported elsewhere, e.g. here: https://github.com/palantir/tslint/issues/3827. A similar issue was raised, and later fixed, in the `tslint-eslint-rules` library here: https://github.com/buzinas/tslint-eslint-rules/issues/165.

**Comment by Sergiioo** [comment]
Fixed in version 2.0.4
